import defineActionTypes from '../utils/defineActionTypes';

export default defineActionTypes({
  /*
   * View model
   */

  LAYOUT_VIEW: `
    SAVE_LAYOUT
  `,

  TEXTS_VIEW: `
    SELECT_CHAPTER
    SELECT_TEXT
    SCROLL_SET
    SCROLL_LINE
    SCROLL_PARAGRAPH
    SYNC_SCROLL
    SYNC_SELECTIONS
    UPDATE_LINES_HEIGHTS
    UPDATE_CLIENT_HEIGHT
    UPDATE_SELECTIONS
    RECALC_OFFSETS
    RECALC_SYNCED_TEXTS
    RECALC_ALIGNED_TEXT_SETS
    RECALC_LINE_MERGES
  `,

  /*
   * Data model
   */

  TEXTS_DATA: `
    UPDATE
    ADD
    REMOVE
    MERGE_NEXT_LINE
    UNMERGE_NEXT_LINE
    DISUNITE_NEXT_LINE
    UNIT_NEXT_LINE
    MERGE_NEXT_SRC_LINE
    UNMERGE_NEXT_SRC_LINE
    DISUNITE_NEXT_SRC_LINE
    UNIT_NEXT_SRC_LINE
  `,

  CHAPTERS_DATA: `
    UPDATE
    ADD
    REMOVE
  `,

  CONFIG_DATA: `
    SAVE_SCROLL_CONFIG
  `,
})
